apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmops_demo 
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: llmops_demo # Add this label
  template:
    metadata:
      labels:
        app: llmops_demo
    spec:
      containers:
        - name: llmops_demo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
          ports:
            - containerPort: 8081
